/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import express from 'express';
import path from 'path';
import { createServer as createViteServer } from 'vite';
import dotenv from 'dotenv';
import fs from 'fs';
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, addDoc, getDocs, query, orderBy, limit, Timestamp } from 'firebase/firestore';
import { M5Telemetry } from './src/types';

dotenv.config();

const app = express();
app.use(express.json());

const PORT = 3000;

// In-Memory Fallback DB in case Firebase is not fully configured or throws exceptions
let inMemoryTelemetry: M5Telemetry[] = [
  {
    timestamp: "2026-07-08 Wed 17:57:59",
    system_status: "fall_danger",
    temperature: 29.49,
    humidity: 68.09,
    motion: 1,
    person_detected: true,
    volume_status: true,
    fall_detected: true,
    acceleration: 2.874785
  },
  {
    timestamp: "2026-07-08 Wed 17:57:06",
    system_status: "heat_warning",
    temperature: 30.35,
    humidity: 79.36,
    motion: 1,
    person_detected: true,
    volume_status: false,
    fall_detected: false,
    acceleration: 1.040342
  },
  {
    timestamp: "2026-07-08 Wed 17:56:40",
    system_status: "safe",
    temperature: 25.22,
    humidity: 44.81,
    motion: 0,
    person_detected: false,
    volume_status: false,
    fall_detected: false,
    acceleration: 1.056055
  }
];

// Initialize Firebase SDK using the JSON config generated by set_up_firebase
let firestoreDb: any = null;
let firebaseActive = false;

try {
  const configPath = path.join(process.cwd(), 'firebase-applet-config.json');
  if (fs.existsSync(configPath)) {
    const firebaseConfig = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    const firebaseApp = initializeApp(firebaseConfig);
    firestoreDb = getFirestore(firebaseApp);
    firebaseActive = true;
    console.log('Firebase Firestore initialized successfully.');
  } else {
    console.warn('firebase-applet-config.json not found. Falling back to in-memory telemetry logs.');
  }
} catch (error) {
  console.error('Failed to initialize Firebase:', error);
}

// API Routes

// GET /api/telemetry - Retrieve latest telemetry list
app.get('/api/telemetry', async (req, res) => {
  if (firebaseActive && firestoreDb) {
    try {
      const telemetryCol = collection(firestoreDb, 'telemetry');
      // Query the latest 15 logs ordered by createdAt timestamp
      const q = query(telemetryCol, orderBy('createdAt', 'desc'), limit(15));
      const querySnapshot = await getDocs(q);
      
      const logs: M5Telemetry[] = [];
      querySnapshot.forEach((doc) => {
        const data = doc.data();
        logs.push({
          timestamp: data.timestamp || new Date().toISOString(),
          system_status: data.system_status || 'safe',
          temperature: typeof data.temperature === 'number' ? data.temperature : 22,
          humidity: typeof data.humidity === 'number' ? data.humidity : 50,
          motion: typeof data.motion === 'number' ? data.motion : 0,
          person_detected: typeof data.person_detected === 'boolean' ? data.person_detected : false,
          volume_status: typeof data.volume_status === 'boolean' ? data.volume_status : false,
          fall_detected: typeof data.fall_detected === 'boolean' ? data.fall_detected : false,
          acceleration: typeof data.acceleration === 'number' ? data.acceleration : 1.0
        });
      });

      // If Firebase successfully returned logs, serve them. Otherwise, fall back.
      if (logs.length > 0) {
        return res.json({
          success: true,
          firebase: true,
          data: logs
        });
      }
    } catch (err: any) {
      console.error('Firestore fetch error, falling back to in-memory:', err.message);
    }
  }

  // Fallback to in-memory list
  res.json({
    success: true,
    firebase: false,
    data: inMemoryTelemetry
  });
});

// POST /api/sensors/report - Receive incoming JSON report from M5Stack or Simulator
app.post('/api/sensors/report', async (req, res) => {
  const payload = req.body;

  // Build a validated telemetry record
  const record: M5Telemetry = {
    timestamp: payload.timestamp || new Date().toLocaleString(),
    system_status: (payload.system_status === 'heat_warning' || payload.system_status === 'fall_danger') 
      ? payload.system_status 
      : 'safe',
    temperature: typeof payload.temperature === 'number' ? parseFloat(payload.temperature.toFixed(2)) : 25.0,
    humidity: typeof payload.humidity === 'number' ? parseFloat(payload.humidity.toFixed(2)) : 45.0,
    motion: payload.motion === 1 ? 1 : 0,
    person_detected: typeof payload.person_detected === 'boolean' ? payload.person_detected : false,
    volume_status: typeof payload.volume_status === 'boolean' ? payload.volume_status : false,
    fall_detected: typeof payload.fall_detected === 'boolean' ? payload.fall_detected : false,
    acceleration: typeof payload.acceleration === 'number' ? parseFloat(payload.acceleration.toFixed(4)) : 1.0
  };

  // 1. Save to Firebase Firestore if active
  let savedToFirebase = false;
  if (firebaseActive && firestoreDb) {
    try {
      const telemetryCol = collection(firestoreDb, 'telemetry');
      await addDoc(telemetryCol, {
        ...record,
        createdAt: Timestamp.now()
      });
      savedToFirebase = true;
    } catch (err: any) {
      console.error('Failed to write report to Firestore:', err.message);
    }
  }

  // 2. Always prepend to in-memory array to guarantee active preview fallback
  inMemoryTelemetry.unshift(record);
  if (inMemoryTelemetry.length > 30) {
    inMemoryTelemetry = inMemoryTelemetry.slice(0, 30);
  }

  res.json({
    status: 'success',
    savedToFirebase,
    record
  });
});

// Serve frontend assets using Vite middleware or Static files
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`AESA Server listening on http://localhost:${PORT}`);
  });
}

startServer();
